"""Extract source-bound cut paths only; no supplier thumbnails or artwork copied."""
import json, hashlib, math
from pathlib import Path
from pypdf import PdfReader
from pypdf.generic import ContentStream
ROOT=Path(__file__).resolve().parents[2]
BASE=ROOT/'output/supplier-imports/wmd-gulvfolie-2026-09-30'
plan=json.loads((ROOT/'output/gulvfolie-2026-09-30/presentation-plan.json').read_text())
payload=json.loads((BASE/'draft/payload.json').read_text())
docs=json.loads((BASE/'documents/inspection.json').read_text())['documents']
def multiply(a,b):
 return [a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]]
def extract(page):
 paths=[]
 def visit(stream,res,initial):
  state=(initial,False);stack=[];path=[]
  def point(x,y):
   a,b,c,d,e,f=state[0];return [a*float(x)+c*float(y)+e,b*float(x)+d*float(y)+f]
  for args,op in ContentStream(stream,page.pdf).operations:
   if op==b'q':stack.append(state)
   elif op==b'Q':state=stack.pop()
   elif op==b'cm':state=(multiply(state[0],list(map(float,args))),state[1])
   elif op in [b'CS',b'RG',b'K',b'G']:
    color=res.get('/ColorSpace',{}).get(args[0]) if op==b'CS' else None
    color=color.get_object() if color else None
    state=(state[0],bool((color and color[0]=='/Separation' and str(color[1]).lower() in ['/cutkontur','/cutcontour']) or (op==b'K' and list(args)==[0,1,0,0])))
   elif op in [b'm',b'l']:path.append([op.decode().upper(),*point(*args)])
   elif op==b'c':path.append(['C',*sum([point(*args[i:i+2]) for i in range(0,6,2)],[])])
   elif op==b'h':path.append(['Z'])
   elif op==b're':
    x,y,w,h=map(float,args);path.extend([['M',*point(x,y)],['L',*point(x+w,y)],['L',*point(x+w,y+h)],['L',*point(x,y+h)],['Z']])
   elif op in [b'S',b's',b'B',b'b',b'B*',b'b*',b'f',b'f*',b'n']:
    if op in [b's',b'b',b'b*']:path.append(['Z'])
    if state[1] and op in [b'S',b's',b'B',b'b',b'B*',b'b*'] and len(path)>3:
     if path[-1][0]!='Z' and path[0][1:]==path[-1][-2:]:path.append(['Z'])
     if path[-1][0]=='Z':paths.append(path)
    path=[]
   elif op==b'Do':
    obj=res['/XObject'][args[0]].get_object()
    if obj.get('/Subtype')=='/Form':visit(obj,obj.get('/Resources',res),multiply(state[0],obj.get('/Matrix',[1,0,0,1,0,0])))
 visit(page.get_contents(),page['/Resources'],[1,0,0,1,0,0])
 return paths

def bounds(path):
 pts=[];cur=None
 for c in path:
  if c[0] in ['M','L']:cur=c[1:];pts.append(cur)
  elif c[0]=='C':
   p0=cur;p1=c[1:3];p2=c[3:5];p3=c[5:7];ts={0,1}
   for j in [0,1]:
    a=-p0[j]+3*p1[j]-3*p2[j]+p3[j];b=2*(p0[j]-2*p1[j]+p2[j]);cc=p1[j]-p0[j]
    if abs(a)<1e-12:
     if abs(b)>1e-12:ts.add(-cc/b)
    elif b*b-4*a*cc>=0:
     ts.update([(-b+math.sqrt(b*b-4*a*cc))/(2*a),(-b-math.sqrt(b*b-4*a*cc))/(2*a)])
   for t in ts:
    if 0<=t<=1:pts.append([(1-t)**3*p0[j]+3*(1-t)**2*t*p1[j]+3*(1-t)*t*t*p2[j]+t**3*p3[j] for j in [0,1]])
   cur=p3
 return min(p[0] for p in pts),min(p[1] for p in pts),max(p[0] for p in pts),max(p[1] for p in pts)
registry=[]
for shape,row in zip(plan['shapes'],payload['shapes']):
 assert shape['label']==row['name']
 item={'id':shape['id'],'valueId':row['id'],'label':shape['label'],'kind':'freeform' if shape['id']=='free-form' else 'rectangle' if shape['id']=='free-size' else 'preset'}
 if item['kind']=='preset':
  candidates=[d for d in docs if d['productUrl'] in [b['sourceUrl'] for b in shape['bindings']]]
  assert candidates,shape['id']
  doc=candidates[0];data=(BASE/doc['path']).read_bytes();assert hashlib.sha256(data).hexdigest()==doc['sha256']
  paths=extract(PdfReader(BASE/doc['path']).pages[0]);assert paths,shape['id']
  # Supplier dimension arrows/legend strokes are open. Keep the largest closed
  # spot-colour outline, never the source page rectangle or typography.
  path=max(paths,key=lambda p:(bounds(p)[2]-bounds(p)[0])*(bounds(p)[3]-bounds(p)[1]))
  x0,y0,x1,y1=bounds(path);w=x1-x0;h=y1-y0
  norm=[]
  for c in path:
   norm.append(c[0]+' '.join(str(round((c[i]-x0)/w if i%2 else (y1-c[i])/w,8)) for i in range(1,len(c))))
  if shape['id']=='round':
   norm=['M0.5 0 C0.7761423749 0 1 0.2238576251 1 0.5 C1 0.7761423749 0.7761423749 1 0.5 1 C0.2238576251 1 0 0.7761423749 0 0.5 C0 0.2238576251 0.2238576251 0 0.5 0 Z'];w=h=1
  item.update({'ratio':w/h,'path':' '.join(norm),'sourceSha256':doc['sha256'],'sourceUrl':doc['sourceUrl'],'sourceOutlineCount':len(paths)})
 registry.append(item)
text='// Generated by scripts/product-templates/extract-gulvfolie-contours.py.\nexport const gulvfolieShapes = '+json.dumps(registry,ensure_ascii=False,indent=2)+' as const;\n'
(ROOT/'src/lib/designer/gulvfolieShapes.ts').write_text(text)
(ROOT/'output/qa/wide-format-templates-2026-10-01/source-contours.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2))
print([(r['id'],round(r.get('ratio',0),5),r.get('sourceOutlineCount')) for r in registry])
