export type MachineProfileCategory = "wide_format" | "digital_sheet" | "offset";

export interface MachineProfileCandidate {
  id: string;
  manufacturer: string;
  model: string;
  category: MachineProfileCategory;
  mode: "SHEET" | "ROLL";
  machineDraft: Record<string, string | number | boolean>;
  ratedPerformance: string;
  verifiedFacts: string[];
  sourceUrl: string;
  sourceLabel: string;
}

const rollDraft = (width: number) => ({
  mode: "ROLL",
  roll_width_mm: width,
  margin_left_mm: 0,
  margin_right_mm: 0,
  margin_top_mm: 0,
  margin_bottom_mm: 0,
  duplex_supported: false,
  setup_waste_sheets: 1,
  run_waste_pct: 3,
  setup_time_min: 10,
  m2_per_hour: 0,
  machine_rate_per_hour: 0,
});

const sheetDraft = (width: number, height: number, duplex = true) => ({
  mode: "SHEET",
  sheet_width_mm: width,
  sheet_height_mm: height,
  margin_left_mm: 0,
  margin_right_mm: 0,
  margin_top_mm: 0,
  margin_bottom_mm: 0,
  duplex_supported: duplex,
  setup_waste_sheets: 5,
  run_waste_pct: 2,
  setup_time_min: 10,
  sheets_per_hour: 0,
  machine_rate_per_hour: 0,
});

const hpLatexSource = "https://support.hp.com/au-en/product/product-specs/hp-latex-800-printer/model/38347888";
const xeroxVersantSource = "https://www.xerox.com/en-si/digital-printing/digital-presses/xerox-versant-280";
const konicaSource = "https://www.konicaminolta.eu/eu-en/professional-printing/devices/production-printing/accuriopress-c7100-enhanced";

export const MACHINE_PROFILE_CANDIDATES: MachineProfileCandidate[] = [
  {
    id: "hp-latex-800",
    manufacturer: "HP",
    model: "Latex 800",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1625), name: "HP Latex 800" },
    ratedPerformance: "20 m²/t ved Production Quality, 8 pass; flere kvalitetsniveauer findes",
    verifiedFacts: ["Maks. mediebredde 1.625 mm", "Officielle hastigheder varierer fra 14 til 122 m²/t efter kvalitet"],
    sourceUrl: hpLatexSource,
    sourceLabel: "HP produktspecifikation",
  },
  {
    id: "hp-latex-800w",
    manufacturer: "HP",
    model: "Latex 800 W",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1625), name: "HP Latex 800 W" },
    ratedPerformance: "Kvalitetsafhængig; hvid blæk har egne hastighedstilstande",
    verifiedFacts: ["Maks. mediebredde 1.625 mm", "Hvid blæk og overcoat"],
    sourceUrl: "https://digitalprinting.hp.com/content/dam/sites/possibility-city/latex-800-w-printer/bucket-pages/specifications/HP%20Latex%20800%20W%20Printer%20Data%20Sheet%20UK.pdf",
    sourceLabel: "HP datablad",
  },
  {
    id: "roland-vg3-640",
    manufacturer: "Roland DG",
    model: "TrueVIS VG3-640",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1625), name: "Roland TrueVIS VG3-640" },
    ratedPerformance: "Skal måles i den valgte printtilstand",
    verifiedFacts: ["Mediebredde 335,3-1.625 mm", "Opløsning op til 1.200 dpi"],
    sourceUrl: "https://www.rolanddg.eu/-/media/roland-emea/files/brochures/vg3/truevis_vg3_brochure_en.pdf/",
    sourceLabel: "Roland DG brochure",
  },
  {
    id: "roland-vg3-540",
    manufacturer: "Roland DG",
    model: "TrueVIS VG3-540",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1371), name: "Roland TrueVIS VG3-540" },
    ratedPerformance: "Skal måles i den valgte printtilstand",
    verifiedFacts: ["Mediebredde 295-1.371 mm", "Integreret print og skæring"],
    sourceUrl: "https://www.rolanddg.eu/-/media/roland-emea/files/brochures/vg3/truevis_vg3_brochure_en.pdf/",
    sourceLabel: "Roland DG brochure",
  },
  {
    id: "mimaki-cjv330-160",
    manufacturer: "Mimaki",
    model: "CJV330-160",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1620), name: "Mimaki CJV330-160" },
    ratedPerformance: "Skal vælges efter blæk, medie og kvalitet",
    verifiedFacts: ["1,6 m print-og-skær-maskine", "Produktionshastigheden er kvalitetsafhængig"],
    sourceUrl: "https://www.mimakieurope.com/products/solvent/cjv330-160/",
    sourceLabel: "Mimaki produktside",
  },
  {
    id: "mimaki-jv330-160",
    manufacturer: "Mimaki",
    model: "JV330-160",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1620), name: "Mimaki JV330-160" },
    ratedPerformance: "Skal vælges efter blæk, medie og kvalitet",
    verifiedFacts: ["1,6 m eco-solvent printer", "Hastighed skal knyttes til en konkret kvalitetstilstand"],
    sourceUrl: "https://www.mimakieurope.com/products/solvent/cjv330-160/",
    sourceLabel: "Mimaki produktside",
  },
  {
    id: "canon-colorado-m",
    manufacturer: "Canon",
    model: "Colorado M-serien",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1625), name: "Canon Colorado M-serien" },
    ratedPerformance: "Konfiguration og kvalitetstilstand skal bekræftes",
    verifiedFacts: ["64-tommer rulleplatform", "UVgel-platform med modulære konfigurationer"],
    sourceUrl: "https://www.canon-europe.com/business/products/large-format-printers/colorado-m-series/",
    sourceLabel: "Canon produktside",
  },
  {
    id: "epson-sc-s80600l",
    manufacturer: "Epson",
    model: "SureColor SC-S80600L",
    category: "wide_format",
    mode: "ROLL",
    machineDraft: { ...rollDraft(1626), name: "Epson SureColor SC-S80600L" },
    ratedPerformance: "Skal måles i den valgte printtilstand",
    verifiedFacts: ["64-tommer signage-printer", "Flere blækkonfigurationer og kvalitetsniveauer"],
    sourceUrl: "https://www.epson.eu/en_EU/products/printers/large-format/surecolor-s80600l/p/29191",
    sourceLabel: "Epson produktside",
  },
  {
    id: "xerox-versant-280",
    manufacturer: "Xerox",
    model: "Versant 280",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Xerox Versant 280" },
    ratedPerformance: "Op til 80 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Op til 80 A4-sider/min.", "Medier op til 400 g/m² afhængigt af konfiguration"],
    sourceUrl: xeroxVersantSource,
    sourceLabel: "Xerox produktside",
  },
  {
    id: "xerox-versant-4100",
    manufacturer: "Xerox",
    model: "Versant 4100",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Xerox Versant 4100" },
    ratedPerformance: "Op til 100 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Produktionsprinter til højere volumen", "Langark kræver relevant feeder-konfiguration"],
    sourceUrl: "https://www.xerox.com/en-us/digital-printing/digital-presses/xerox-versant-4100",
    sourceLabel: "Xerox produktside",
  },
  {
    id: "xerox-iridesse",
    manufacturer: "Xerox",
    model: "Iridesse",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Xerox Iridesse" },
    ratedPerformance: "Op til 120 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Seks printstationer", "CMYK plus specialtonere afhængigt af konfiguration"],
    sourceUrl: "https://www.xerox.com/en-us/digital-printing/digital-presses/iridesse-production-press",
    sourceLabel: "Xerox produktside",
  },
  {
    id: "ricoh-pro-c7500",
    manufacturer: "Ricoh",
    model: "Pro C7500",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Ricoh Pro C7500" },
    ratedPerformance: "Op til 85 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Femte farvestation", "Produktionshastighed skal valideres mod papirvægt"],
    sourceUrl: "https://www.ricoh-europe.com/media/pro%20c7500%20eu%20brochure_tcm100-76615.pdf",
    sourceLabel: "Ricoh brochure",
  },
  {
    id: "ricoh-pro-c9500",
    manufacturer: "Ricoh",
    model: "Pro C9500",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Ricoh Pro C9500" },
    ratedPerformance: "Op til 135 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Højvolumen digital farveproduktion", "Driftstal skal sættes ud fra faktisk mediemix"],
    sourceUrl: "https://www.ricoh-europe.com/media/20231107_031506_pro_c9500_brochure_final_tcm100-76611.pdf",
    sourceLabel: "Ricoh brochure",
  },
  {
    id: "canon-imagepress-v1000",
    manufacturer: "Canon",
    model: "imagePRESS V1000",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Canon imagePRESS V1000" },
    ratedPerformance: "Op til 100 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Digital farveproduktionsprinter", "Automatisk duplex; konfiguration skal bekræftes"],
    sourceUrl: "https://www.canon-europe.com/business/products/production-printers/digital-presses/imagepress-v1000/",
    sourceLabel: "Canon produktside",
  },
  {
    id: "canon-imagepress-v1350",
    manufacturer: "Canon",
    model: "imagePRESS V1350",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Canon imagePRESS V1350" },
    ratedPerformance: "Op til 135 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Højvolumen digital farveproduktion", "Nettoproduktion afhænger af job og efterbehandling"],
    sourceUrl: "https://www.canon-europe.com/business/products/production-printers/digital-presses/imagepress-v1350/",
    sourceLabel: "Canon produktside",
  },
  {
    id: "konica-c7100",
    manufacturer: "Konica Minolta",
    model: "AccurioPress C7100 Enhanced",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330.2, 487.7), name: "Konica Minolta AccurioPress C7100 Enhanced" },
    ratedPerformance: "100 A4-sider/min. eller op til 53 SRA3-sider/min.",
    verifiedFacts: ["Maks. standardark 330,2 × 487,7 mm", "52-400 g/m² i duplex afhængigt af konfiguration"],
    sourceUrl: konicaSource,
    sourceLabel: "Konica Minolta produktside",
  },
  {
    id: "konica-c14000e",
    manufacturer: "Konica Minolta",
    model: "AccurioPress C14000e",
    category: "digital_sheet",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(330, 488), name: "Konica Minolta AccurioPress C14000e" },
    ratedPerformance: "Op til 140 A4-sider/min.; mål ark/t for jeres medie",
    verifiedFacts: ["Højvolumen tonerproduktion", "Langark og efterbehandling afhænger af konfiguration"],
    sourceUrl: "https://www.konicaminolta.eu/eu-en/professional-printing/devices/production-printing/accuriopress-c14000e",
    sourceLabel: "Konica Minolta produktside",
  },
  {
    id: "heidelberg-xl106",
    manufacturer: "Heidelberg",
    model: "Speedmaster XL 106",
    category: "offset",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(750, 1060, false), name: "Heidelberg Speedmaster XL 106", setup_waste_sheets: 150, setup_time_min: 35, run_waste_pct: 1 },
    ratedPerformance: "Op til 18.000 ark/t i standard tekniske data; produktionsmåling anbefales",
    verifiedFacts: ["Maks. ark 750 × 1.060 mm", "Maks. printformat 740 × 1.050 mm"],
    sourceUrl: "https://www.heidelberg.com/global/en/print_and_packaging/products/offset_printing/format_70_x_100/speedmaster_xl_106/product_information_12/speedmaster_xl_106_commercial_printing.jsp",
    sourceLabel: "Heidelberg produktside",
  },
  {
    id: "komori-lithrone-g40",
    manufacturer: "Komori",
    model: "Lithrone G40",
    category: "offset",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(750, 1050, false), name: "Komori Lithrone G40 advance", setup_waste_sheets: 150, setup_time_min: 40, run_waste_pct: 1 },
    ratedPerformance: "Op til 17.200 ark/t; produktionsmåling anbefales",
    verifiedFacts: ["Maks. ark 750 × 1.050 mm", "Maks. printformat 710 × 1.020 mm"],
    sourceUrl: "https://www.komori.com/en/global/product/press/offset/advance/lithrone_g40_advance.html",
    sourceLabel: "Komori produktside",
  },
  {
    id: "rmgt-970",
    manufacturer: "RMGT",
    model: "970-serien",
    category: "offset",
    mode: "SHEET",
    machineDraft: { ...sheetDraft(650, 965, false), name: "RMGT 970-serien", setup_waste_sheets: 150, setup_time_min: 40, run_waste_pct: 1 },
    ratedPerformance: "Op til 16.000 ark/t som straight press; produktionsmåling anbefales",
    verifiedFacts: ["Maks. ark 650 × 965 mm", "Straight- og perfecting-konfigurationer findes"],
    sourceUrl: "https://www.ryobi-group.co.jp/graphic/english/news/2020/07/006989.php",
    sourceLabel: "RMGT produktside",
  },
];

export const MACHINE_PROFILE_CATEGORY_LABELS: Record<MachineProfileCategory, string> = {
  wide_format: "Storformat",
  digital_sheet: "Digital ark",
  offset: "Offset",
};
