// Generated by scripts/generate-storefront-image-variants.py. Originals stay untouched.
export const STOREFRONT_IMAGE_VARIANTS: Record<string, {width: number; src: string}[]> = {
  "products/bannere": [
    {
      "width": 96,
      "src": "/storefront-images/products/bannere-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/bannere-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/bannere-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/bannere-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/bannere-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/bannere-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/bannere-1280.webp"
    }
  ],
  "products/beachflag": [
    {
      "width": 96,
      "src": "/storefront-images/products/beachflag-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/beachflag-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/beachflag-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/beachflag-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/beachflag-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/beachflag-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/beachflag-1280.webp"
    }
  ],
  "products/displayplakater": [
    {
      "width": 96,
      "src": "/storefront-images/products/displayplakater-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/displayplakater-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/displayplakater-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/displayplakater-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/displayplakater-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/displayplakater-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/displayplakater-1280.webp"
    }
  ],
  "products/flyers": [
    {
      "width": 96,
      "src": "/storefront-images/products/flyers-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/flyers-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/flyers-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/flyers-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/flyers-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/flyers-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/flyers-1280.webp"
    }
  ],
  "products/foldere": [
    {
      "width": 96,
      "src": "/storefront-images/products/foldere-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/foldere-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/foldere-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/foldere-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/foldere-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/foldere-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/foldere-1280.webp"
    }
  ],
  "products/folie": [
    {
      "width": 96,
      "src": "/storefront-images/products/folie-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/folie-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/folie-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/folie-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/folie-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/folie-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/folie-1280.webp"
    }
  ],
  "products/haefter": [
    {
      "width": 96,
      "src": "/storefront-images/products/haefter-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/haefter-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/haefter-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/haefter-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/haefter-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/haefter-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/haefter-1280.webp"
    }
  ],
  "products/klistermaerker": [
    {
      "width": 96,
      "src": "/storefront-images/products/klistermaerker-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/klistermaerker-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/klistermaerker-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/klistermaerker-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/klistermaerker-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/klistermaerker-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/klistermaerker-1280.webp"
    }
  ],
  "products/messeudstyr": [
    {
      "width": 96,
      "src": "/storefront-images/products/messeudstyr-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/messeudstyr-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/messeudstyr-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/messeudstyr-480.webp"
    },
    {
      "width": 512,
      "src": "/storefront-images/products/messeudstyr-512.webp"
    }
  ],
  "products/plakater": [
    {
      "width": 96,
      "src": "/storefront-images/products/plakater-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/plakater-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/plakater-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/plakater-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/plakater-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/plakater-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/plakater-1280.webp"
    }
  ],
  "products/salgsmapper": [
    {
      "width": 96,
      "src": "/storefront-images/products/salgsmapper-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/salgsmapper-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/salgsmapper-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/salgsmapper-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/salgsmapper-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/salgsmapper-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/salgsmapper-1280.webp"
    }
  ],
  "products/skilte": [
    {
      "width": 96,
      "src": "/storefront-images/products/skilte-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/skilte-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/skilte-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/skilte-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/skilte-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/skilte-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/skilte-1280.webp"
    }
  ],
  "products/visitkort": [
    {
      "width": 96,
      "src": "/storefront-images/products/visitkort-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/products/visitkort-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/products/visitkort-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/products/visitkort-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/products/visitkort-640.webp"
    },
    {
      "width": 960,
      "src": "/storefront-images/products/visitkort-960.webp"
    },
    {
      "width": 1280,
      "src": "/storefront-images/products/visitkort-1280.webp"
    }
  ],
  "categories/category-posters": [
    {
      "width": 96,
      "src": "/storefront-images/categories/category-posters-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/categories/category-posters-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/categories/category-posters-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/categories/category-posters-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/categories/category-posters-640.webp"
    },
    {
      "width": 800,
      "src": "/storefront-images/categories/category-posters-800.webp"
    }
  ],
  "categories/category-print": [
    {
      "width": 96,
      "src": "/storefront-images/categories/category-print-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/categories/category-print-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/categories/category-print-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/categories/category-print-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/categories/category-print-640.webp"
    },
    {
      "width": 800,
      "src": "/storefront-images/categories/category-print-800.webp"
    }
  ],
  "categories/category-stickers": [
    {
      "width": 96,
      "src": "/storefront-images/categories/category-stickers-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/categories/category-stickers-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/categories/category-stickers-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/categories/category-stickers-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/categories/category-stickers-640.webp"
    },
    {
      "width": 800,
      "src": "/storefront-images/categories/category-stickers-800.webp"
    }
  ],
  "categories/category-textile": [
    {
      "width": 96,
      "src": "/storefront-images/categories/category-textile-96.webp"
    },
    {
      "width": 192,
      "src": "/storefront-images/categories/category-textile-192.webp"
    },
    {
      "width": 320,
      "src": "/storefront-images/categories/category-textile-320.webp"
    },
    {
      "width": 480,
      "src": "/storefront-images/categories/category-textile-480.webp"
    },
    {
      "width": 640,
      "src": "/storefront-images/categories/category-textile-640.webp"
    },
    {
      "width": 800,
      "src": "/storefront-images/categories/category-textile-800.webp"
    }
  ]
};
