import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  classifyTemplateBindings,
  generateTemplateResolutionPlan,
  sha256Json,
} from "../build-wmd-sales-folder-template-resolution-plan.js";

const TEST_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const REPOSITORY_ROOT = path.resolve(TEST_DIRECTORY, "../../..");
const RUN_DIRECTORY = path.join(
  REPOSITORY_ROOT,
  "tmp/supplier-imports/wmd-sales-folders-20260831-full"
);
const REVIEW_DIRECTORY = path.join(RUN_DIRECTORY, "review");
const OUTPUT_PATH = path.join(REVIEW_DIRECTORY, "template-resolution-plan.json");
const PROPOSED_CLASSIFICATION_COUNTS = Object.freeze({
  base_verified: 3170,
  pending_title_only: 306,
  exact_verified_rebind: 52,
  collateral_original_after_bad_alias_quarantine: 140,
  indirect_pending_title_rebind: 2,
  extended_exact_evidence: 22,
});

let contextPromise;

async function actualContext() {
  if (!contextPromise) {
    contextPromise = Promise.all([
      generateTemplateResolutionPlan({ runDirectory: RUN_DIRECTORY, writeOutput: false }),
      fs.readFile(path.join(REVIEW_DIRECTORY, "template-geometry-audit.json"), "utf8").then(JSON.parse),
      fs.readFile(path.join(REVIEW_DIRECTORY, "template-geometry-supplement.json"), "utf8").then(JSON.parse),
    ]).then(([generated, audit, supplement]) => ({ generated, audit, supplement }));
  }
  return contextPromise;
}

function sha256Bytes(value) {
  return createHash("sha256").update(value).digest("hex");
}

function proposedAudit(plan, audit) {
  const included = new Set(plan.bindingClassifications.map((entry) => entry.bindingKey));
  return {
    ...audit,
    bindingAudits: audit.bindingAudits.filter((row) => included.has(row.bindingKey)),
  };
}

test("production resolution plan deterministically excludes the CD product and covers all 3,692 proposed bindings", async () => {
  const { generated } = await actualContext();
  const { plan } = generated;
  assert.equal(plan.kind, "wmd_sales_folder_template_resolution_plan");
  assert.equal(plan.schemaVersion, 1);
  assert.equal(plan.reviewState, "pending_review");
  assert.deepEqual(plan.approval, { approved: false, reviewer: null, reviewedAt: null });
  assert.deepEqual(plan.approvedEntryHashes, []);
  assert.deepEqual(plan.counts.classifications, PROPOSED_CLASSIFICATION_COUNTS);
  assert.equal(plan.counts.totalBindings, 3692);
  assert.equal(plan.counts.baseVerifiedBindings, 3170);
  assert.equal(plan.counts.recoveredBindingsPendingReview, 522);
  assert.equal(plan.counts.extendedEvidenceFamilies, 4);
  assert.equal(plan.counts.extendedEvidenceTargets, 10);
  assert.equal(plan.counts.unresolvedBindings, 0);
  assert.deepEqual(plan.filteredCandidates.templateProjection, {
    inputBindings: 3692,
    candidateBindings: 3692,
    withheldBindings: 0,
  });
  assert.deepEqual(plan.filteredCandidates.compatibility, {
    inputSelections: 3692,
    candidateSelections: 3692,
    withheldSelections: 0,
  });
  assert.deepEqual(plan.filteredCandidates.proposedPriceRows, {
    inputRows: 108348,
    candidateRows: 108348,
    withheldRows: 0,
  });
  assert.equal(plan.bindingClassifications.length, 3692);
  assert.equal(plan.bindingClassificationFingerprints.length, 3692);
  assert.equal(new Set(plan.bindingClassifications.map((entry) => entry.bindingKey)).size, 3692);
  assert.equal(new Set(plan.bindingClassificationFingerprints.map((entry) => entry.entrySha256)).size, 3692);
  assert.deepEqual(
    plan.bindingClassificationFingerprints,
    plan.bindingClassifications.map((entry) => ({
      bindingKey: entry.bindingKey,
      entrySha256: sha256Json(entry),
    }))
  );
  assert.equal(plan.inputEvidence.extendedEvidenceFiles.length, 13);
  assert.ok(plan.inputEvidence.extendedEvidenceFiles.every((entry) => /^[a-f0-9]{64}$/.test(entry.sha256)));
  assert.equal(plan.catalogScope.counts.excluded.documentBindings, 52);
  assert.equal(plan.sourceScopeProjection.rawBindingCount, 3744);
  assert.equal(plan.sourceScopeProjection.proposedBindingCount, 3692);
  assert.equal(plan.sourceScopeProjection.rawSupplierEvidenceMutated, false);
  assert.equal(JSON.stringify(plan.bindingClassifications).includes("cd-135x135"), false);
  assert.equal(JSON.stringify(plan.extendedEvidence).includes("mappe_cd"), false);
  assert.ok(Object.values(plan.prohibitedActionsPerformed).every((value) => value === false));
});

test("generated bytes match the checked pending artifact and its separate SHA-256 sidecar", async () => {
  const { generated } = await actualContext();
  const bytes = await fs.readFile(OUTPUT_PATH);
  const sidecar = await fs.readFile(`${OUTPUT_PATH}.sha256`, "utf8");
  const actualSha256 = sha256Bytes(bytes);
  assert.equal(generated.outputSha256, actualSha256);
  assert.equal(sidecar, `${actualSha256}  template-resolution-plan.json\n`);
  assert.deepEqual(JSON.parse(bytes), generated.plan);
});

test("extended evidence fails closed when a target identity drifts even with recomputed fingerprints", async () => {
  const { generated, audit, supplement } = await actualContext();
  const extended = structuredClone(generated.plan.extendedEvidence);
  const family = extended.families.find((entry) => entry.resolutionMode === "original");
  const target = family.targetEntries[0];
  target.resolvedTemplate.sha256 = "a".repeat(64);
  extended.targetFingerprints = extended.families
    .flatMap((entry) => entry.targetEntries.map((candidate) => ({
      targetKey: candidate.targetKey,
      entrySha256: sha256Json(candidate),
    })))
    .sort((left, right) => left.targetKey.localeCompare(right.targetKey, "en", { numeric: true }));
  extended.familyFingerprints = extended.families.map((entry) => ({
    familyKey: entry.familyKey,
    familySha256: sha256Json(entry),
  }));
  assert.throws(
    () => classifyTemplateBindings({
      audit: proposedAudit(generated.plan, audit),
      supplement,
      baseAuditSha256: generated.plan.inputEvidence.baseAudit.sha256,
      titleSupplementSha256: generated.plan.inputEvidence.geometrySupplement.sha256,
      extendedEvidence: extended,
    }),
    /Extended original changes template identity/
  );
});

test("direct rebind source ambiguity is refused instead of choosing an arbitrary PDF", async () => {
  const { generated, audit, supplement } = await actualContext();
  const directRecord = generated.plan.bindingClassifications.find(
    (entry) => entry.classification === "exact_verified_rebind"
  );
  const source = audit.bindingAudits.find(
    (row) => row.bindingKey === directRecord.newTemplate.bindingKey
  );
  assert.ok(source);
  const ambiguousSource = structuredClone(source);
  ambiguousSource.bindingKey = "https://www.wir-machen-druck.de/ambiguous-source.html|ambiguous-material";
  ambiguousSource.sourceUrl = "https://www.wir-machen-druck.de/ambiguous-source.html";
  ambiguousSource.sourceProductId = "ambiguous-source";
  ambiguousSource.sourceSku = "ambiguous-source";
  ambiguousSource.materialId = "ambiguous-material";
  ambiguousSource.paperKey = "ambiguous-paper";
  ambiguousSource.templateSourceUrl = "https://www.wir-machen-druck.de/tpl/ambiguous-source.pdf";
  ambiguousSource.templateLocalRelativePath = "documents/source-pdfs/ambiguous-source.pdf";
  ambiguousSource.templateSha256 = "b".repeat(64);
  const scopedAudit = proposedAudit(generated.plan, audit);
  const ambiguousAudit = { ...scopedAudit, bindingAudits: [...scopedAudit.bindingAudits, ambiguousSource] };
  assert.throws(
    () => classifyTemplateBindings({
      audit: ambiguousAudit,
      supplement,
      baseAuditSha256: generated.plan.inputEvidence.baseAudit.sha256,
      titleSupplementSha256: generated.plan.inputEvidence.geometrySupplement.sha256,
      extendedEvidence: generated.plan.extendedEvidence,
    }),
    /AMBIGUOUS_EXACT_VERIFIED_REBIND_SOURCE/
  );
});

test("approved-title dependency drift is refused before any classification can be promoted", async () => {
  const { generated, audit, supplement } = await actualContext();
  assert.throws(
    () => classifyTemplateBindings({
      audit: proposedAudit(generated.plan, audit),
      supplement,
      baseAuditSha256: generated.plan.inputEvidence.baseAudit.sha256,
      titleSupplementSha256: "c".repeat(64),
      extendedEvidence: generated.plan.extendedEvidence,
    }),
    /Extended evidence title-supplement hash drifted/
  );
});
