import { fabric } from 'fabric';
import { jsPDF } from 'jspdf';
import { svg2pdf } from 'svg2pdf.js';
import { PDFDocument, PDFName, PDFArray, PDFRawStream, PDFObjectCopier, BlendMode, concatTransformationMatrix, pushGraphicsState, popGraphicsState, drawObject, setGraphicsState } from 'pdf-lib';
import type { DocumentSpec } from './types';
import { computeExportCropRect } from './computeExportCropRect';
import { drawCutContoursAsVector } from './exportVectorPdfBackground';
import { createProductionColorTransform, type ProductionOutputProfile, type ProductionColorTransform } from './productionColor';
import { discoverProductionFonts, outlineProductionSvgText } from './productionFonts';
import { addProductionOutputIntent, embedProductionRaster, multiplyAffine, pdfPageToObjectMatrix, importedVisibleBox, preserveImportedOutputIntent, productionRasterScale, setProductionPageBoxes, tagGeneratedRgbPage, type AffineMatrix } from './productionPdfObjects';
import { SRGB_PROFILE_URL } from '../../color/iccProofing';

export interface ProductionPdfWarning { code: string; message: string; objectIndex?: number; effectivePpi?: number }
export interface ProductionPdfContext {
  documentSpec: DocumentSpec;
  fabricCanvas: fabric.Canvas | null;
  includeBleed?: boolean;
  displayMetrics?: { mmToPx: number; pasteboardPaddingPx: number };
  outputProfile?: ProductionOutputProfile;
  colorMode?: 'convert_cmyk' | 'preserve_rgb';
  renderingIntent?: 0 | 1 | 2 | 3;
  blackPointCompensation?: boolean;
}
export interface ProductionPdfResult {
  bytes: Uint8Array;
  filename: string;
  warnings: ProductionPdfWarning[];
  vectorObjects: number;
  outlinedTextRuns: number;
  rasterObjects: number;
  importedPdfPages: number;
  colorMode: 'convert_cmyk' | 'preserve_rgb';
  outputProfile?: { id: string; name: string };
}

const SNAPSHOT_PROPERTIES = ['data', '__isGuide', '__isGuideLabel', '__isPdfTemplate', '__isDocumentBackground', '__isStaticFrame', '__isCutContour'];
const BLENDS: Record<string, BlendMode> = { 'source-over': BlendMode.Normal, multiply: BlendMode.Multiply, screen: BlendMode.Screen,
  overlay: BlendMode.Overlay, darken: BlendMode.Darken, lighten: BlendMode.Lighten, 'color-dodge': BlendMode.ColorDodge,
  'color-burn': BlendMode.ColorBurn, 'hard-light': BlendMode.HardLight, 'soft-light': BlendMode.SoftLight,
  difference: BlendMode.Difference, exclusion: BlendMode.Exclusion };

function isGuide(object: any) { return object.__isGuide || object.__isGuideLabel || object.__isPdfTemplate || (object.__isStaticFrame && !object.__isDocumentBackground); }
function objectChildren(object: any): any[] { return object.getObjects?.() || []; }
function rasterReason(object: any): string | null {
  if (object.type === 'image') return 'Billede';
  if (object.shadow) return 'Skygge';
  if (object.direction === 'rtl') return 'Højre-mod-venstre tekst';
  if (object.strokeUniform && (object.scaleX !== 1 || object.scaleY !== 1)) return 'Skaleret streg med fast bredde';
  if (object.fill && typeof object.fill !== 'string') return 'Forløb eller mønster';
  if (object.stroke && typeof object.stroke !== 'string') return 'Forløb eller mønster i streg';
  if (object.path && ['text', 'i-text', 'textbox'].includes(object.type)) return 'Tekst på kurve';
  for (const child of objectChildren(object)) { const reason = rasterReason(child); if (reason) return reason; }
  return null;
}

/** Only an SVG generated by our Fabric snapshot is accepted, never uploaded SVG markup. */
function createObjectSvg(object: fabric.Object, crop: ReturnType<typeof computeExportCropRect>): SVGSVGElement {
  const markup = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${crop.pdfWidthMm * 72 / 25.4}" height="${crop.pdfHeightMm * 72 / 25.4}" viewBox="${crop.cropLeft} ${crop.cropTop} ${crop.cropWidth} ${crop.cropHeight}">${object.toSVG()}</svg>`;
  const parsed = new DOMParser().parseFromString(markup, 'image/svg+xml');
  if (parsed.querySelector('parsererror')) throw new Error('Objektets SVG kunne ikke læses.');
  const allowed = new Set(['svg', 'g', 'path', 'rect', 'circle', 'ellipse', 'polygon', 'polyline', 'line', 'defs', 'clippath', 'text', 'tspan']);
  for (const element of Array.from(parsed.querySelectorAll('*'))) {
    if (!allowed.has(element.localName.toLowerCase())) throw new Error(`SVG-effekten ${element.localName} kræver rasterisering.`);
    for (const attribute of Array.from(element.attributes)) {
      if (/^on/i.test(attribute.name) || /href$/i.test(attribute.name) || /url\(\s*['"]?(?!#)/i.test(attribute.value)) throw new Error('Eksterne SVG-referencer understøttes ikke i vektoreksport.');
    }
  }
  return document.importNode(parsed.documentElement, true) as unknown as SVGSVGElement;
}

function installCmykVectorPaint(pdf: jsPDF, conversion: ProductionColorTransform) {
  const cache = new Map<string, string[]>();
  for (const method of ['setFillColor', 'setDrawColor', 'setTextColor'] as const) {
    const original = pdf[method].bind(pdf) as (...args: any[]) => any;
    (pdf as any)[method] = (...args: any[]) => {
      if (args.length === 4) return original(...args);
      let rgb: number[];
      if (typeof args[0] === 'string' && args.length === 1 && !/^\d/.test(args[0])) rgb = new fabric.Color(args[0]).getSource().slice(0, 3);
      else if (args.length === 1) rgb = [args[0], args[0], args[0]].map(Number);
      else rgb = args.slice(0, 3).map(Number);
      if (rgb.length !== 3 || rgb.some(n => !Number.isFinite(n))) throw new Error('Ukendt farve i vektoreksport.');
      const key = rgb.join(',');
      let cmyk = cache.get(key);
      if (!cmyk) {
        // Single-channel black for text/line art; images take the normal ICC transform.
        cmyk = rgb.every(n => n === 0) ? ['0', '0', '0', '1'] : Array.from(conversion.convert(new Uint8Array(rgb))).map(n => (n / 255).toFixed(6));
        cache.set(key, cmyk);
      }
      return original(...cmyk);
    };
  }
}

function snapshotObject(object: fabric.Object): Promise<fabric.Object> {
  return new Promise((resolve, reject) => {
    try { object.clone((clone: fabric.Object) => clone ? resolve(clone) : reject(new Error('Designobjekt kunne ikke kopieres.')), SNAPSHOT_PROPERTIES); }
    catch (error) { reject(error); }
  });
}

function imagePixels(object: fabric.Object, pixelsPerMm: number, maxTrimMm: number) {
  const bounds = object.getBoundingRect(true, true);
  const shadow = object.shadow as fabric.Shadow | null;
  const scaling = object.getObjectScaling();
  const padding = shadow ? 4 + Math.max(Math.abs(shadow.offsetX) + shadow.blur * 2, Math.abs(shadow.offsetY) + shadow.blur * 2) * Math.max(scaling.scaleX, scaling.scaleY) : 2;
  const left = bounds.left - padding, top = bounds.top - padding;
  const width = Math.ceil(bounds.width + 2 * padding), height = Math.ceil(bounds.height + 2 * padding);
  const scale = productionRasterScale(width, height, pixelsPerMm, maxTrimMm);
  const canvas = new fabric.StaticCanvas(document.createElement('canvas'), { width, height, enableRetinaScaling: false, renderOnAddRemove: false, skipOffscreen: false });
  const oldComposite = object.globalCompositeOperation;
  try {
    object.globalCompositeOperation = 'source-over';
    canvas.add(object);
    canvas.setViewportTransform([1, 0, 0, 1, -left, -top]);
    const raster = canvas.toCanvasElement(scale.multiplier, { left: 0, top: 0, width, height });
    const context = raster.getContext('2d', { willReadFrequently: true });
    if (!context) throw new Error('Rasterdata kunne ikke læses.');
    const image = context.getImageData(0, 0, raster.width, raster.height);
    return { image, left, top, width, height, ...scale };
  } finally {
    canvas.remove(object);
    canvas.dispose();
    object.globalCompositeOperation = oldComposite;
  }
}

/** Shared production builder for a local download and immutable order artwork.
 * It never samples the proof overlay and never asserts PDF/X conformance.
 */
export async function createProductionPdf(context: ProductionPdfContext): Promise<ProductionPdfResult> {
  const { documentSpec: spec, fabricCanvas } = context;
  if (!fabricCanvas) throw new Error('Designfladen er ikke klar.');
  const colorMode = context.colorMode || 'convert_cmyk';
  // The explicit export mode owns this choice even when callers retain a selected
  // CMYK profile for preview. An RGB supplier file must not advertise that target.
  const outputProfile = colorMode === 'convert_cmyk' ? context.outputProfile : undefined;
  if (colorMode === 'convert_cmyk' && !outputProfile) throw new Error('Vælg en gyldig produktionsprofil før CMYK-eksport.');
  const metrics = context.displayMetrics || { mmToPx: 2, pasteboardPaddingPx: 100 };
  const includeBleed = context.includeBleed !== false;
  const crop = computeExportCropRect({ includeBleed, width_mm: spec.width_mm, height_mm: spec.height_mm, bleed_mm: spec.bleed_mm || 0,
    ...metrics, canvasWidthPx: (spec.width_mm + 2 * (spec.bleed_mm || 0)) * metrics.mmToPx + metrics.pasteboardPaddingPx * 2,
    canvasHeightPx: (spec.height_mm + 2 * (spec.bleed_mm || 0)) * metrics.mmToPx + metrics.pasteboardPaddingPx * 2 });
  if (!crop.isValid || ![crop.pdfWidthMm, crop.pdfHeightMm, metrics.mmToPx].every(n => Number.isFinite(n) && n > 0)) throw new Error(crop.error || 'Ugyldig produktionsstørrelse.');
  const width = crop.pdfWidthMm * 72 / 25.4, height = crop.pdfHeightMm * 72 / 25.4;
  // jsPDF has a 14400-point page limit. Fail explicitly rather than silently resizing large signage.
  if (Math.max(width, height) > 14400) throw new Error('PDF over 5080 mm kræver en aftalt produktionsskalering.');
  const objects = await Promise.all(fabricCanvas.getObjects().filter(obj => !isGuide(obj) && obj.visible !== false).map(snapshotObject));
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([width, height]);
  setProductionPageBoxes(page, spec.width_mm, spec.height_mm, includeBleed ? spec.bleed_mm || 0 : 0);
  const result: ProductionPdfResult = { bytes: new Uint8Array(), filename: `${(spec.name?.trim() && spec.name !== 'Uden titel' ? spec.name.trim() : 'WebPrinter PDF').replace(/[^a-z0-9æøåÆØÅ\s-]/gi, '_')}.pdf`, warnings: [], vectorObjects: 0, outlinedTextRuns: 0, rasterObjects: 0, importedPdfPages: 0, colorMode,
    ...(outputProfile ? { outputProfile: { id: outputProfile.id, name: outputProfile.name } } : {}) };
  const sourceResponse = await fetch(SRGB_PROFILE_URL);
  if (!sourceResponse.ok) throw new Error('sRGB-profilen kunne ikke indlæses.');
  const srgb = new Uint8Array(await sourceResponse.arrayBuffer());
  const srgbRef = pdf.context.register(pdf.context.flateStream(srgb, { N: 3, Alternate: 'DeviceRGB' }));
  const targetRef = outputProfile ? addProductionOutputIntent(pdf, outputProfile) : undefined;
  const conversion = colorMode === 'convert_cmyk' ? await createProductionColorTransform(outputProfile!, context.renderingIntent ?? 1, context.blackPointCompensation !== false) : null;
  const fonts = await discoverProductionFonts();
  const scale = width / crop.cropWidth;
  const canvasToPdf: AffineMatrix = [scale, 0, 0, -scale, -crop.cropLeft * scale, height + crop.cropTop * scale];
  try {
    for (let index = 0; index < objects.length; index++) {
      const object = objects[index] as fabric.Object & Record<string, any>;
      if (object.__isCutContour) continue;
      if (object.__isDocumentBackground) { object.stroke = null; object.strokeWidth = 0; }
      const blend = BLENDS[object.globalCompositeOperation || 'source-over'];
      if (!blend) throw new Error(`Objekt ${index + 1}: kompositionen ${object.globalCompositeOperation} kræver en særskilt eksport.`);
      if (object.data?.kind === 'pdf_page_background' && object.data.originalPdfBytes) {
        if (object.clipPath || (object as any).cropX || (object as any).cropY) throw new Error('Beskåret importeret PDF kræver separat klargøring; originalens vektorer er bevaret i designet.');
        const source = await PDFDocument.load(object.data.originalPdfBytes);
        const sourcePage = source.getPage(object.data.pageIndex || 0);
        if (source.catalog.has(PDFName.of('OCProperties')) || (sourcePage.node.get(PDFName.of('UserUnit')) && sourcePage.node.get(PDFName.of('UserUnit'))?.toString() !== '1')) {
          throw new Error('Importeret PDF med valgfrie lag eller særlig sideskalering kræver særskilt klargøring; originalfilen er uændret.');
        }
        const visibleBox = importedVisibleBox(sourcePage);
        const annotations = sourcePage.node.lookupMaybe(PDFName.of('Annots'), PDFArray);
        if (annotations?.size()) throw new Error('Importeret PDF med annotationer/formularfelter skal klargøres før produktion.');
        const originalIntent = preserveImportedOutputIntent(source, sourcePage);
        const embedded = await pdf.embedPage(sourcePage, visibleBox);
        const sourceGroup = sourcePage.node.get(PDFName.of('Group'));
        if (sourceGroup) {
          await embedded.embed();
          const form = pdf.context.lookup(embedded.ref);
          if (!(form instanceof PDFRawStream)) throw new Error('Importerede PDF-transparensdata kunne ikke bevares.');
          form.dict.set(PDFName.of('Group'), PDFObjectCopier.for(source.context, pdf.context).copy(sourceGroup));
        }
        const matrix = multiplyAffine(canvasToPdf, multiplyAffine(object.calcTransformMatrix() as AffineMatrix,
          pdfPageToObjectMatrix(embedded.width, embedded.height, object.width || 0, object.height || 0, sourcePage.getRotation().angle)));
        page.pushOperators(pushGraphicsState(), concatTransformationMatrix(...matrix));
        page.drawPage(embedded, { x: 0, y: 0, width: embedded.width, height: embedded.height, opacity: object.opacity, blendMode: blend });
        page.pushOperators(popGraphicsState());
        result.importedPdfPages++;
        result.warnings.push({ code: 'imported_pdf_preserved', objectIndex: index, message: originalIntent
          ? `Importeret PDF beholder sine farver og originalprofil ${originalIntent}; indholdet er ikke genkonverteret.`
          : 'Importeret PDF beholder sine eksisterende farver. Ingen oprindelig output intent blev fundet; trykkeriet skal kontrollere farvefortolkningen.' });
        continue;
      }
      let reason = rasterReason(object);
      if (!reason) {
        try {
          const svg = createObjectSvg(object, crop);
          const textRuns = await outlineProductionSvgText(svg, fonts);
          const vector = new jsPDF({ unit: 'pt', format: [width, height], orientation: width > height ? 'landscape' : 'portrait', compress: true, floatPrecision: 8 });
          if (conversion) installCmykVectorPaint(vector, conversion);
          await svg2pdf(svg, vector, { x: 0, y: 0, width, height });
          const vectorPdf = await PDFDocument.load(vector.output('arraybuffer'));
          if (!conversion) tagGeneratedRgbPage(vectorPdf, vectorPdf.getPage(0), srgb);
          const [embedded] = await pdf.embedPdf(vectorPdf, [0]);
          page.drawPage(embedded, { x: 0, y: 0, width, height, blendMode: blend });
          result.vectorObjects++; result.outlinedTextRuns += textRuns;
          continue;
        } catch (error) { reason = error instanceof Error ? error.message : 'Objekteffekt'; }
      }
      const raster = imagePixels(object, metrics.mmToPx, Math.max(spec.width_mm, spec.height_mm));
      const samples = new Uint8Array(raster.image.width * raster.image.height * 3);
      const alpha = new Uint8Array(raster.image.width * raster.image.height);
      for (let pixel = 0; pixel < alpha.length; pixel++) { samples.set(raster.image.data.subarray(pixel * 4, pixel * 4 + 3), pixel * 3); alpha[pixel] = raster.image.data[pixel * 4 + 3]; }
      const pixels = conversion ? conversion.convert(samples) : samples;
      const ref = embedProductionRaster(pdf, raster.image.width, raster.image.height, pixels, alpha, conversion ? targetRef : srgbRef, conversion ? 4 : 3);
      const name = page.node.newXObject('ArtworkImage', ref);
      // ExtGState applies blends at composition time, after isolated object rasterization.
      const state = pdf.context.register(pdf.context.obj({ Type: 'ExtGState', BM: PDFName.of(blend) }));
      const stateName = page.node.newExtGState('ArtworkBlend', state);
      page.pushOperators(pushGraphicsState(), setGraphicsState(stateName), concatTransformationMatrix(raster.width * scale, 0, 0, raster.height * scale,
        (raster.left - crop.cropLeft) * scale, height - (raster.top - crop.cropTop + raster.height) * scale), drawObject(name), popGraphicsState());
      result.rasterObjects++;
      if (reason !== 'Billede' || raster.effectivePpi < raster.targetPpi - 1) result.warnings.push({ code: 'object_rasterized', objectIndex: index,
        message: `Objekt ${index + 1}: ${reason}. Kun dette objekt er rasteriseret ved ${Math.round(raster.effectivePpi)} ppi.`, effectivePpi: raster.effectivePpi });
    }
    await drawCutContoursAsVector(page, pdf, { getObjects: () => objects } as fabric.Canvas, spec, includeBleed, metrics);
    pdf.setTitle(spec.name || 'WebPrinter PDF');
    pdf.setCreator('Webprinter Designer');
    pdf.setSubject(colorMode === 'convert_cmyk' ? 'Production artwork: managed CMYK additions; imported PDF colors preserved' : 'Production artwork: tagged sRGB additions; supplier conversion');
    pdf.setKeywords(['Production artwork', outputProfile?.name || 'sRGB', 'Not PDF/X certified']);
    result.bytes = await pdf.save();
    return result;
  } finally { conversion?.dispose(); }
}
