"""Create display-sized WebP copies without changing any original artwork.

Run with Python + Pillow after adding/changing built-in category/product images.
Uploaded public Storage images are resized by the existing image service instead.
"""
import json
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
WIDTHS = (96, 192, 320, 480, 640, 960, 1280)
manifest = {}
report = []
sources = [(p, 'products') for p in sorted((ROOT / 'src/assets/products').glob('*.png'))]
sources += [(p, 'categories') for p in sorted((ROOT / 'public/design-presets').glob('category-*.webp'))]
for path, group in sources:
    with Image.open(path) as image:
        image = ImageOps.exif_transpose(image).convert('RGBA')
        widths = sorted({min(width, image.width) for width in WIDTHS})
        variants = []
        for width in widths:
            height = max(1, round(image.height * width / image.width))
            destination = ROOT / f'public/storefront-images/{group}/{path.stem}-{width}.webp'
            destination.parent.mkdir(parents=True, exist_ok=True)
            image.resize((width, height), Image.Resampling.LANCZOS).save(destination, 'WEBP', quality=78, method=6)
            variants.append({'width': width, 'src': '/' + str(destination.relative_to(ROOT / 'public'))})
        manifest[f'{group}/{path.stem}'] = variants
        card = next((v for v in variants if v['width'] >= 640), variants[-1])
        report.append({'source': str(path.relative_to(ROOT)), 'originalBytes': path.stat().st_size,
                       'cardBytes': (ROOT / 'public' / card['src'].lstrip('/')).stat().st_size, 'width': card['width']})
(ROOT / 'src/lib/storefront/storefrontImageManifest.ts').write_text(
    '// Generated by scripts/generate-storefront-image-variants.py. Originals stay untouched.\n'
    'export const STOREFRONT_IMAGE_VARIANTS: Record<string, {width: number; src: string}[]> = '
    + json.dumps(manifest, indent=2) + ';\n')
print(json.dumps(report, indent=2))
